[PluginCVars_LowPriority]
r.Shadow.Virtual.Cache.ForceInvalidateDirectional=1

LFN.AutomaticReplayRecording=0
JunoPersistence.AcquirePlayerLock=0

FortAIPawn.ReplicateSimulatedAttributes=1

Fort.SmartObject.Player.EnableIgnoreTimeDiscrepancyWhenUsingSO=true
Fort.ServerIgnoreTimeDiscrepancy=true

Fort.ClientCheckWorldPartitionForLevelStreamingHandshake=true
Fort.ServerCheckWorldPartitionForLevelStreamingHandshake=true

Hurdle.SkipMaxHurdleDamageIgnorableCheck=true

Fort.Assets.ShouldGetAssetKeepInMemoryByDefault=true

Juno.UI.HudLayout=Juno.HUD.Layout.Simplified

# Enable CoDel flow control, with dependencies.
net.FlowControlType=CoDel
net.IpNetDriverUseReceiveThread=1
net.UseRecvMulti=1
net.UseRecvTimestamps=1

p.Chaos.CheckForInterclusterEdgesOnRelease=0
Juno.ConnectivityGraph.UsePartialDestruction=0

[PluginCVars_HighPriority]
AsyncTraceDelegateHitchThresholdMS=0.85
